### ISSUE TITLE
defdf giving unbound variable

### ISSUE THREAD

**Issue by JARS3N** [Lisp-Stat/documentation#6] opened 2021-11-14 22:07 UTC
I was just going through the examples in the documentation and here:

`(defdf iris
	(read-csv "https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/datasets/iris.csv")
	"Edgar Anderson's Iris Data")
`

gives the error "variable IRIS is unbound [condition of type UNBOUND-VARIABLE]"

**Comment by Symbolics** [comment] 2021-11-15 00:03
Hmmm. I can't reproduce this. Can you copy & paste the sequence of commands and their outputs, starting with the `(asdf:load-system :lisp-stat)` command? We'll isolate the problem step-by-step.

**Comment by JARS3N** [comment] 2021-11-15 00:59
LS-USER> (asdf:load-system :lisp-stat)
T
LS-USER> (in-package :ls-user)
#<PACKAGE "LS-USER">
LS-USER> (def max-temps '#(30.1 30.3 30.3 30.8 31.6 31.5 32.7 32.1 32.1 31.4 31.9 31.7 32.2 31.1))
MAX-TEMPS
LS-USER> (def min-temps '#(24.6 25.4 25.1 24.5 23.7 25.6 24.6 24.7 25.0 25.2 25.1 25.6 25.5 25.2))
MIN-TEMPS
LS-USER> (def precipitation '#(0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.0 0.6 0.4 0.0 0.0 ))
PRECIPITATION
LS-USER> (variables)
(MAX-TEMPS MIN-TEMPS PRECIPITATION)
LS-USER> (undef 'max-temps)
MAX-TEMPS
LS-USER> (savevar 'precipitation "precipitation")
(PRECIPITATION)
LS-USER> (savevar '(min-temps precipitation) "sg-weather")
(MIN-TEMPS PRECIPITATION)
LS-USER> (defmethod print-object ((df data-frame) stream)
  "Print the first six rows of DATA-FRAME"
  (let* ((*print-lines* 6)
	     (*print-pretty* t))
    (df:pprint-data-frame df stream nil)))
(setf *print-pretty* t)
(set-pprint-dispatch 'df:data-frame
		     #'(lambda (s df) (pprint-data-frame df s nil)))

WARNING:
   redefining PRINT-OBJECT (#<STANDARD-CLASS DATA-FRAME:DATA-FRAME>
                            #<SB-PCL:SYSTEM-CLASS COMMON-LISP:T>) in DEFMETHOD
NIL
LS-USER> (defparameter v #(1 2 3 4)) ; data vector
(defparameter b #*0110)     ; bits
(defparameter s #(a b c d)) ; symbols
(defparameter plist `(:vector ,v :symbols ,s))

PLIST
LS-USER> (apply #'df plist)
;; VECTOR SYMBOLS
;;      1       A
;;      2       B
;;      3       C
;;      4       D

LS-USER> (plist-df plist)
;; VECTOR SYMBOLS
;;      1       A
;;      2       B
;;      3       C
;;      4       D

LS-USER> (alist-df (plist-alist plist))
;; VECTOR SYMBOLS
;;      1       A
;;      2       B
;;      3       C
;;      4       D

LS-USER> (make-df '(:a :b) '(#(1 2 3) #(10 20 30)))
;; A  B
;; 1 10
;; 2 20
;; 3 30

LS-USER> (matrix-df #(:a :b) #2A((1 2)
	                    (3 4)))
;; A B
;; 1 2
;; 3 4

LS-USER> 
(defdf iris
	(read-csv "https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/datasets/iris.csv")
	"Edgar Anderson's Iris Data"))
`
The variable IRIS is unbound.
   [Condition of type UNBOUND-VARIABLE]

Restarts:
 0: [CONTINUE] Retry using IRIS.
 1: [USE-VALUE] Use specified value.
 2: [STORE-VALUE] Set specified value and use it.
 3: [RETRY] Retry SLIME REPL evaluation request.
 4: [ABORT] Return to sldb level 1.
 5: [SUPERSEDE] Reopen with :if-exists :supersede
 --more--

Backtrace:
  0: (SB-INT:SIMPLE-EVAL-IN-LEXENV IRIS #<NULL-LEXENV>)
  1: (SB-INT:SIMPLE-EVAL-IN-LEXENV (DEFDF IRIS (READ-CSV "https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/datasets/iris.csv") "Edgar Anderson's Iris Data") #<NULL-LEXENV>)
  2: (EVAL (DEFDF IRIS (READ-CSV "https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/datasets/iris.csv") "Edgar Anderson's Iris Data"))
 --more--
`
;; after aborting out of that one I tried to load the R data to try and load MTCARS

LS_USER> rdata:*r-default-datasets*
`Package RDATA does not exist.

  Line: 1, Column: 25, File-Position: 25

  Stream: #<SB-IMPL::STRING-INPUT-STREAM {100590A0B3}>
   [Condition of type SB-INT:SIMPLE-READER-PACKAGE-ERROR]

Restarts:
 0: [CONTINUE] Use the current package, LS-USER.
 1: [RETRY] Retry finding the package.
 2: [USE-VALUE] Specify a different package
 3: [UNINTERN] Read the symbol as uninterned.
 4: [SYMBOL] Specify a symbol to return
 5: [RETRY] Retry SLIME REPL evaluation request.
 --more--

Backtrace:
  0: (SB-IMPL::READER-FIND-PACKAGE "RDATA" #<SB-IMPL::STRING-INPUT-STREAM {100590A0B3}> T)
  1: (SB-IMPL::READ-TOKEN #<SB-IMPL::STRING-INPUT-STREAM {100590A0B3}> #\r)
  2: (SB-IMPL::READ-MAYBE-NOTHING #<SB-IMPL::STRING-INPUT-STREAM {100590A0B3}> #\r)
  3: (SB-IMPL::%READ-PRESERVING-WHITESPACE #<SB-IMPL::STRING-INPUT-STREAM {100590A0B3}> NIL (NIL) T)
  4: (SB-IMPL::%READ-PRESERVING-WHITESPACE #<SB-IMPL::STRING-INPUT-STREAM {100590A0B3}> NIL (NIL) NIL)
  5: (READ #<SB-IMPL::STRING-INPUT-STREAM {100590A0B3}> NIL #<SB-IMPL::STRING-INPUT-STREAM {100590A0B3}> NIL)
 --more--
`
;; So it looks like something isn't being loaded that should be?

**Comment by Symbolics** [comment] 2021-11-15 01:11
Well, that is strange. Let's isolate:

1. What version of SBCL are you running?
2. Have you got the latest version, 2.1, of Lisp-Stat? Check with `(asdf:system-version (asdf:find-system 'lisp-stat))`
3. Are you running a quicklisp version or a clone of the github repo?

It sounds like your version may be out of date. After confirming you've got the latest, try this minimal sequence of forms:

```lisp
; SLIME 2.26.1
CL-USER> (asdf:load-system :lisp-stat)
T
CL-USER> (in-package :ls-user)
#<PACKAGE "LS-USER">
LS-USER> (defdf iris
	(read-csv "https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/datasets/iris.csv")
	"Edgar Anderson's Iris Data")
COMMON-LISP:WARNING: Missing column name was filled in
IRIS
LS-USER> iris
#<DATA-FRAME IRIS (150 observations of 6 variables)
Edgar Anderson's Iris Data>
LS-USER> 
```

**Comment by JARS3N** [comment] 2021-11-15 23:33
; SLIME 2.26.1
CL-USER>  (ql:update-client)
The most up-to-date client, version 2021-02-13, is already installed.
T
~ $ sbcl --version
SBCL 2.0.1.debian
which is the latest version from the repo

**Comment by Symbolics** [comment] 2021-11-15 23:45
The quicklisp client version may be different from the lisp-stat version; in fact they almost certainly will be. Try this:

`(asdf:system-version (asdf:find-system 'lisp-stat))`

if the output is anything other than "2.1", then update the quicklisp distribution (not the client). See the section entitled _To Get Updated Software_ in the [basic commands section of the Quicklisp documentation](https://www.quicklisp.org/beta/#basic-commands).

**Comment by JARS3N** [comment] 2021-11-16 00:25
build SBCL from source to 2.1
;; updated dist via
(ql:update-dist "quicklisp")
:: then had to install via
(ql:quickload "listp-stat")
(asdf:load-system :lisp-stat)
;; then

CL-USER> (asdf:load-system :lisp-stat)
T
CL-USER> (in-package :ls-user)
#<PACKAGE "LS-USER">
LS-USER> (defdf iris
	(read-csv "https://raw.githubusercontent.com/vincentarelbundock/Rdatasets/master/csv/datasets/iris.csv")
	"Edgar Anderson's Iris Data")

COMMON-LISP:WARNING: Missing column name was filled in
IRIS
LS-USER> IRIS
#<DATA-FRAME IRIS (150 observations of 6 variables)
Edgar Anderson's Iris Data>
LS-USER> 

appears to have worked

**Comment by Symbolics** [comment] 2021-11-16 00:27
Great! If there's nothing else then, we'll close this issue and you can open another if you encounter any more problems.

**Closed as completed** 2021-11-16 00:31 UTC
